module GraphQL
  module Define
    module AssignMutationReturnType
      def self.call(target, type = nil, &block)
        if type.nil?
          target.return_type_mode = :generated
          type = GraphQL::ObjectType.define {
            name("#{target.name}Payload")
            description("Autogenerated return type of #{target.name}")
            field :clientMutationId, types.String, "A unique identifier for the client performing the mutation.", property: :client_mutation_id
            mutation(target)
            instance_eval(&block)
          }
        end

        target.return_type = type
      end
    end
  end
end
